baseURL = 'http://example.org/'
languageCode = 'es'
title = 'Juan'
theme = "shibui"

[params]
  author = "Your Name"
  email = "your.email@example.com"

[menu]
  [[menu.main]]
    name = ""
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = ""
    url = "/about/"
    weight = 2